import image5 from "./assets/google-pixel-8-pro.webp";
import image2 from "./assets/iphone-15-pro-max.webp";
import image1 from "./assets/iPhone15.webp";
import image9 from "./assets/motorola-edge-2023.webp";
import image6 from "./assets/oneplus-11-5g.webp";
import image10 from "./assets/oppo-find-x6-pro.webp";
import image3 from "./assets/samsung-galaxy-s23-ultra.webp";
import image4 from "./assets/samsung-galaxy-z-fold-5.webp";
import image8 from "./assets/sony-xperia-1-v.webp";
import image7 from "./assets/xiaomi-13-pro.webp";

export const DATA = [
  {
    id: "1",
    name: "iPhone 15",
    price: 799,
    image: image1,
    capacity: "128GB",
    brand: "Apple",
    frontCamera: "12MP",
    rearCamera: "48MP",
    screenSize: "6.1 inch",
    battery: "3349 mAh",
    chip: "A16 Bionic",
    os: "iOS 17",
    weight: "171g",
  },
  {
    id: "2",
    name: "iPhone 15 Pro Max",
    price: 1199,
    image: image2,
    capacity: "256GB",
    brand: "Apple",
    frontCamera: "12MP",
    rearCamera: "48MP + 12MP + 12MP",
    screenSize: "6.7 inch",
    battery: "4422 mAh",
    chip: "A17 Pro",
    os: "iOS 17",
    weight: "221g",
  },
  {
    id: "3",
    name: "Samsung Galaxy S23 Ultra",
    price: 1199,
    image: image3,
    capacity: "256GB",
    brand: "Samsung",
    frontCamera: "12MP",
    rearCamera: "200MP + 12MP + 10MP + 10MP",
    screenSize: "6.8 inch",
    battery: "5000 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "234g",
  },
  {
    id: "4",
    name: "Samsung Galaxy Z Fold 5",
    price: 1799,
    image: image4,
    capacity: "256GB",
    brand: "Samsung",
    frontCamera: "10MP",
    rearCamera: "50MP + 12MP + 10MP",
    screenSize: "7.6 inch (folded)",
    battery: "4400 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "253g",
  },
  {
    id: "5",
    name: "Google Pixel 8 Pro",
    price: 999,
    image: image5,
    capacity: "128GB",
    brand: "Google",
    frontCamera: "10.5MP",
    rearCamera: "50MP + 48MP + 12MP",
    screenSize: "6.7 inch",
    battery: "5000 mAh",
    chip: "Google Tensor G3",
    os: "Android 14",
    weight: "213g",
  },
  {
    id: "6",
    name: "OnePlus 11 5G",
    price: 749,
    image: image6,
    capacity: "128GB",
    brand: "OnePlus",
    frontCamera: "16MP",
    rearCamera: "50MP + 48MP + 32MP",
    screenSize: "6.7 inch",
    battery: "5000 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "205g",
  },
  {
    id: "7",
    name: "Xiaomi 13 Pro",
    price: 999,
    image: image7,
    capacity: "256GB",
    brand: "Xiaomi",
    frontCamera: "32MP",
    rearCamera: "50MP + 50MP + 50MP",
    screenSize: "6.73 inch",
    battery: "4820 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "229g",
  },
  {
    id: "8",
    name: "Sony Xperia 1 V",
    price: 1299,
    image: image8,
    capacity: "256GB",
    brand: "Sony",
    frontCamera: "12MP",
    rearCamera: "48MP + 12MP + 12MP",
    screenSize: "6.5 inch",
    battery: "5000 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "225g",
  },
  {
    id: "9",
    name: "Motorola Edge+ (2023)",
    price: 999,
    image: image9,
    capacity: "256GB",
    brand: "Motorola",
    frontCamera: "60MP",
    rearCamera: "200MP + 50MP + 12MP",
    screenSize: "6.7 inch",
    battery: "5100 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "203g",
  },
  {
    id: "10",
    name: "Oppo Find X6 Pro",
    price: 1199,
    image: image10,
    capacity: "256GB",
    brand: "Oppo",
    frontCamera: "32MP",
    rearCamera: "50MP + 50MP + 50MP",
    screenSize: "6.82 inch",
    battery: "5000 mAh",
    chip: "Snapdragon 8 Gen 2",
    os: "Android 13",
    weight: "218g",
  },
];
